//-----------自动生成------------
namespace ET
{
    public static partial class GameRegister
    {
        public static void RegisterEntitySystem()
        {
            EntitySystemSingleton.RegisterEntitySystem<ET.LocationManagerComponentSystem.ET_LocationManagerComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.LocationOneTypeSystem.ET_LocationOneType_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.LockInfoSystem.ET_LockInfo_ET_ActorId_ET_CoroutineLock_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.LockInfoSystem.ET_LockInfo_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.MessageLocationSenderComponentSystem.ET_MessageLocationSenderComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.MessageLocationSenderOneTypeSystem.ET_MessageLocationSenderOneType_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.MessageLocationSenderOneTypeSystem.ET_MessageLocationSenderOneType_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.MessageLocationSenderSystem.ET_MessageLocationSender_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.MessageLocationSenderSystem.ET_MessageLocationSender_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.AOIEntitySystem2.ET_AOIEntity_int_Unity_Mathematics_float3_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.AOIEntitySystem2.ET_AOIEntity_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.CellSystem.ET_Cell_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.CellSystem.ET_Cell_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ConsoleComponentSystem.ET_ConsoleComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ModeContextSystem.ET_ModeContext_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ModeContextSystem.ET_ModeContext_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.DBComponentSystem.ET_DBComponent_string_string_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.HttpComponentSystem.ET_HttpComponent_string_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.HttpComponentSystem.ET_HttpComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.SessionUserEntityComponentSystem.ET_SessionUserEntityComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.SessionUserEntityComponentSystem.ET_SessionUserEntityComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.UserEntitySystem.ET_UserEntity_string_long_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.UserOfflineOutTimeComponentSystem.ET_UserOfflineOutTimeComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.UserOfflineOutTimeComponentSystem.ET_UserOfflineOutTimeComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.LoginInfoRecordComponentSystem.ET_LoginInfoRecordComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.LoginInfoRecordComponentSystem.ET_LoginInfoRecordComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.TokenComponentSystem.ET_TokenComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.UserSessionComponentSystem.ET_UserSessionComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.UserSessionComponentSystem.ET_UserSessionComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.UserSessionTimeoutComponentSystem.ET_UserSessionTimeoutComponent_long_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.UserSessionTimeoutComponentSystem.ET_UserSessionTimeoutComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.MoveComponentSystem.ET_MoveComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.MoveComponentSystem.ET_MoveComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ProcessOuterSenderSystem.ET_ProcessOuterSender_System_Net_IPEndPoint_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ProcessOuterSenderSystem.ET_ProcessOuterSender_UpdateSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ProcessOuterSenderSystem.ET_ProcessOuterSender_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.PathfindingComponentSystem.ET_PathfindingComponent_string_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.PathfindingComponentSystem.ET_PathfindingComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.RobotManagerComponentSystem.ET_RobotManagerComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.RobotManagerComponentSystem.ET_RobotManagerComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.RouterComponentSystem.ET_RouterComponent_System_Net_IPEndPoint_string_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.RouterComponentSystem.ET_RouterComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.RouterComponentSystem.ET_RouterComponent_UpdateSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.RouterNodeSystem.ET_RouterNode_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.RouterNodeSystem.ET_RouterNode_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.WatcherComponentSystem.ET_WatcherComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.AIComponentSystem.ET_AIComponent_int_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.AIComponentSystem.ET_AIComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ProcessInnerSenderSystem.ET_ProcessInnerSender_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ProcessInnerSenderSystem.ET_ProcessInnerSender_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ProcessInnerSenderSystem.ET_ProcessInnerSender_UpdateSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.CoroutineLockComponentSystem.ET_CoroutineLockComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.CoroutineLockComponentSystem.ET_CoroutineLockComponent_UpdateSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.CoroutineLockQueueSystem.ET_CoroutineLockQueue_long_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.CoroutineLockQueueSystem.ET_CoroutineLockQueue_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.CoroutineLockQueueTypeSystem.ET_CoroutineLockQueueType_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.CoroutineLockSystem.ET_CoroutineLock_long_long_int_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.CoroutineLockSystem.ET_CoroutineLock_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.MailBoxComponentSystem.ET_MailBoxComponent_int_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.MailBoxComponentSystem.ET_MailBoxComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.NetComponentSystem.ET_NetComponent_ET_IKcpTransport_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.NetComponentSystem.ET_NetComponent_UpdateSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.NetComponentSystem.ET_NetComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.SessionAcceptTimeoutComponentSystem.ET_SessionAcceptTimeoutComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.SessionAcceptTimeoutComponentSystem.ET_SessionAcceptTimeoutComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.SessionIdleCheckerComponentSystem.ET_SessionIdleCheckerComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.SessionIdleCheckerComponentSystem.ET_SessionIdleCheckerComponent_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.SessionSystem.ET_Session_ET_AService_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.SessionSystem.ET_Session_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ObjectWaitSystem.ET_ObjectWait_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.ObjectWaitSystem.ET_ObjectWait_DestroySystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.TimerComponentSystem.ET_TimerComponent_AwakeSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.TimerComponentSystem.ET_TimerComponent_UpdateSystem>();
            EntitySystemSingleton.RegisterEntitySystem<ET.UnitSystem.ET_Unit_int_AwakeSystem>();
        }
    }
}
