//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public class AIConfigConfigCategory : TableConfigCategoryBase<AIConfig>
    {
        private static AIConfigConfigCategory instance;
        public static AIConfigConfigCategory Instance { get { return instance ??= new AIConfigConfigCategory(); } }
        private AIConfigConfigCategory() { }

        public override AIConfig Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbAIConfig.Get(id);
        }
        public override AIConfig GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbAIConfig.GetOrDefault(id);
        }
        public override List<AIConfig> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbAIConfig.DataList;
        }
    }   
}