//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class AIRobotConfig : TableConfigBase<AIRobotTable>
    {
        private static AIRobotConfig instance;
        public static AIRobotConfig Instance { get { return instance ??= new AIRobotConfig(); } }

        public override AIRobotTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbAIRobot.Get(id);
        }
        public override AIRobotTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbAIRobot.GetOrDefault(id);
        }
        public override List<AIRobotTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbAIRobot.DataList;
        }
    }   
}