//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public class GlobalConstConfigCategory : TableConfigCategoryBase<GlobalConst>
    {
        private static GlobalConstConfigCategory instance;
        public static GlobalConstConfigCategory Instance { get { return instance ??= new GlobalConstConfigCategory(); } }
        private GlobalConstConfigCategory() { }

        public GlobalConst Data
        {
            get
            {
                return TableConfigManager.Instance.ConfigTables.TbGlobalConst.Data;
            }
        }
    }   
}