//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public static partial class GlobalConstConfig
    {
        public static GlobalConstTable Data
        {
            get
            {
                return TableConfigManager.Instance.ConfigTables.TbGlobalConst.Data;
            }
        }
    }   
}