//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public class LubanTestConfigCategory : TableConfigCategoryBase<LubanTest>
    {
        private static LubanTestConfigCategory instance;
        public static LubanTestConfigCategory Instance { get { return instance ??= new LubanTestConfigCategory(); } }
        private LubanTestConfigCategory() { }

        public override LubanTest Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbLubanTest.Get(id);
        }
        public override LubanTest GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbLubanTest.GetOrDefault(id);
        }
        public override List<LubanTest> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbLubanTest.DataList;
        }
    }   
}