//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class MonsterConfig : TableConfigBase<MonsterTable>
    {
        private static MonsterConfig instance;
        public static MonsterConfig Instance { get { return instance ??= new MonsterConfig(); } }

        public override MonsterTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbMonster.Get(id);
        }
        public override MonsterTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbMonster.GetOrDefault(id);
        }
        public override List<MonsterTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbMonster.DataList;
        }
    }   
}