//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class RoleSkillSetConfig : TableConfigBase<RoleSkillSetTable>
    {
        private static RoleSkillSetConfig instance;
        public static RoleSkillSetConfig Instance { get { return instance ??= new RoleSkillSetConfig(); } }

        public override RoleSkillSetTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbRoleSkillSet.Get(id);
        }
        public override RoleSkillSetTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbRoleSkillSet.GetOrDefault(id);
        }
        public override List<RoleSkillSetTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbRoleSkillSet.DataList;
        }
    }   
}