//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class RoleConfig : TableConfigBase<RoleTable>
    {
        private static RoleConfig instance;
        public static RoleConfig Instance { get { return instance ??= new RoleConfig(); } }

        public override RoleTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbRole.Get(id);
        }
        public override RoleTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbRole.GetOrDefault(id);
        }
        public override List<RoleTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbRole.DataList;
        }
    }   
}