//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class SkillConfig : TableConfigBase<SkillTable>
    {
        private static SkillConfig instance;
        public static SkillConfig Instance { get { return instance ??= new SkillConfig(); } }

        public override SkillTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbSkill.Get(id);
        }
        public override SkillTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbSkill.GetOrDefault(id);
        }
        public override List<SkillTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbSkill.DataList;
        }
    }   
}