//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class StartSceneConfig : TableConfigBase<StartSceneTable>
    {
        private static StartSceneConfig instance;
        public static StartSceneConfig Instance { get { return instance ??= new StartSceneConfig(); } }

        public override StartSceneTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartScene.Get(id);
        }
        public override StartSceneTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartScene.GetOrDefault(id);
        }
        public override List<StartSceneTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbStartScene.DataList;
        }
    }   
}