//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public class StartProcessConfigConfigCategory : TableConfigCategoryBase<StartProcessConfig>
    {
        private static StartProcessConfigConfigCategory instance;
        public static StartProcessConfigConfigCategory Instance { get { return instance ??= new StartProcessConfigConfigCategory(); } }
        private StartProcessConfigConfigCategory() { }

        public override StartProcessConfig Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartProcessConfig.Get(id);
        }
        public override StartProcessConfig GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartProcessConfig.GetOrDefault(id);
        }
        public override List<StartProcessConfig> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbStartProcessConfig.DataList;
        }
    }   
}