//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class StartZoneConfig : TableConfigBase<StartZoneTable>
    {
        private static StartZoneConfig instance;
        public static StartZoneConfig Instance { get { return instance ??= new StartZoneConfig(); } }

        public override StartZoneTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartZone.Get(id);
        }
        public override StartZoneTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartZone.GetOrDefault(id);
        }
        public override List<StartZoneTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbStartZone.DataList;
        }
    }   
}