//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public class StartSceneConfigConfigCategory : TableConfigCategoryBase<StartSceneConfig>
    {
        private static StartSceneConfigConfigCategory instance;
        public static StartSceneConfigConfigCategory Instance { get { return instance ??= new StartSceneConfigConfigCategory(); } }
        private StartSceneConfigConfigCategory() { }

        public override StartSceneConfig Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartSceneConfig.Get(id);
        }
        public override StartSceneConfig GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartSceneConfig.GetOrDefault(id);
        }
        public override List<StartSceneConfig> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbStartSceneConfig.DataList;
        }
    }   
}