//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class StartProcessConfig : TableConfigBase<StartProcessTable>
    {
        private static StartProcessConfig instance;
        public static StartProcessConfig Instance { get { return instance ??= new StartProcessConfig(); } }

        public override StartProcessTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartProcess.Get(id);
        }
        public override StartProcessTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartProcess.GetOrDefault(id);
        }
        public override List<StartProcessTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbStartProcess.DataList;
        }
    }   
}