//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class StartMachineConfig : TableConfigBase<StartMachineTable>
    {
        private static StartMachineConfig instance;
        public static StartMachineConfig Instance { get { return instance ??= new StartMachineConfig(); } }

        public override StartMachineTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartMachine.Get(id);
        }
        public override StartMachineTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartMachine.GetOrDefault(id);
        }
        public override List<StartMachineTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbStartMachine.DataList;
        }
    }   
}