//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public class StartMachineConfigConfigCategory : TableConfigCategoryBase<StartMachineConfig>
    {
        private static StartMachineConfigConfigCategory instance;
        public static StartMachineConfigConfigCategory Instance { get { return instance ??= new StartMachineConfigConfigCategory(); } }
        private StartMachineConfigConfigCategory() { }

        public override StartMachineConfig Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartMachineConfig.Get(id);
        }
        public override StartMachineConfig GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbStartMachineConfig.GetOrDefault(id);
        }
        public override List<StartMachineConfig> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbStartMachineConfig.DataList;
        }
    }   
}