//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public class UnitConfigConfigCategory : TableConfigCategoryBase<UnitConfig>
    {
        private static UnitConfigConfigCategory instance;
        public static UnitConfigConfigCategory Instance { get { return instance ??= new UnitConfigConfigCategory(); } }
        private UnitConfigConfigCategory() { }

        public override UnitConfig Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbUnitConfig.Get(id);
        }
        public override UnitConfig GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbUnitConfig.GetOrDefault(id);
        }
        public override List<UnitConfig> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbUnitConfig.DataList;
        }
    }   
}