//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Collections.Generic;

namespace ET
{
    public sealed class UnitConfig : TableConfigBase<UnitTable>
    {
        private static UnitConfig instance;
        public static UnitConfig Instance { get { return instance ??= new UnitConfig(); } }

        public override UnitTable Get(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbUnit.Get(id);
        }
        public override UnitTable GetOrDefault(int id)
        {
            return TableConfigManager.Instance.ConfigTables.TbUnit.GetOrDefault(id);
        }
        public override List<UnitTable> GetDataList()
        {
            return TableConfigManager.Instance.ConfigTables.TbUnit.DataList;
        }
    }   
}